//! ${API_NAME} â€” graduated MCP server from a workflow-stored API pattern
//!
//! Generated from workflow:api_graduate. Single tool, statically wired
//! to one upstream HTTP API. Credentials read from environment at call time
//! (skipped when CRED_ENV_VAR is empty, e.g. for public APIs).

use anyhow::{Context, Result};
use rmcp::{
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::*,
    schemars::{self, JsonSchema},
    serde_json,
    tool, tool_handler, tool_router,
    ErrorData as McpError, ServerHandler, ServiceExt,
};
use serde::{Deserialize, Serialize};

// â”€â”€â”€ PATTERN-DERIVED CONSTANTS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Filled in by workflow:api_graduate at scaffold time.

const API_NAME: &str = "${API_NAME}";
const API_DESCRIPTION: &str = "${API_DESCRIPTION}";
const URL_PATTERN: &str = "${URL_PATTERN}";
const METHOD: &str = "${METHOD}";
const CRED_ENV_VAR: &str = "${CRED_ENV_VAR_NAME}"; // empty string = no auth required
const CRED_HEADER: &str = "${CRED_HEADER}";
const CRED_PREFIX: &str = "${CRED_PREFIX}";

// â”€â”€â”€ INPUT SCHEMA (derived from URL placeholders + body template) â”€â”€â”€â”€
// schemars generates the JSON schema; rmcp surfaces it via list_tools.

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct CallArgs {
    ${INPUT_FIELDS}
}

// â”€â”€â”€ HANDLER â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

#[derive(Clone)]
pub struct ApiTool {
    http: reqwest::Client,
    tool_router: ToolRouter<Self>,
}

#[tool_router(router = tool_router)]
impl ApiTool {
    pub fn new() -> Self {
        Self {
            http: reqwest::Client::builder()
                .user_agent(format!(
                    "{}/{} (Mozilla/5.0)",
                    API_NAME,
                    env!("CARGO_PKG_VERSION")
                ))
                .build()
                .expect("reqwest client"),
            tool_router: Self::tool_router(),
        }
    }

    #[tool(name = "${API_NAME}", description = "${API_DESCRIPTION}")]
    pub async fn call_tool(
        &self,
        params: Parameters<CallArgs>,
    ) -> Result<CallToolResult, McpError> {
        let args = params.0;

        // Build URL by substituting placeholders from args.
        let url = ${URL_BUILDER_EXPR};

        // Build request.
        let mut req = self.http.request(
            METHOD.parse().unwrap_or(reqwest::Method::GET),
            &url,
        );

        // Inject credential ONLY if configured (empty CRED_ENV_VAR = public API).
        if !CRED_ENV_VAR.is_empty() {
            let cred = std::env::var(CRED_ENV_VAR).map_err(|_| {
                McpError::invalid_request(
                    format!("Missing required env var: {}", CRED_ENV_VAR),
                    None,
                )
            })?;
            req = req.header(CRED_HEADER, format!("{}{}", CRED_PREFIX, cred));
        }

        // (Optional, generated only if the API has a body template)
        // ${BODY_BUILDER}

        // Dispatch and pass through.
        let resp = req.send().await.map_err(|e| {
            McpError::internal_error(format!("HTTP request failed: {}", e), None)
        })?;

        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();

        if !status.is_success() {
            return Err(McpError::internal_error(
                format!("Upstream returned {}: {}", status, body),
                None,
            ));
        }

        // Pretty-print JSON if possible; fall back to raw text.
        let formatted = match serde_json::from_str::<serde_json::Value>(&body) {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap_or(body),
            Err(_) => body,
        };

        Ok(CallToolResult::success(vec![Content::text(formatted)]))
    }
}

#[tool_handler(router = self.tool_router)]
impl ServerHandler for ApiTool {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            protocol_version: ProtocolVersion::V_2024_11_05,
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            server_info: Implementation {
                name: API_NAME.to_string(),
                version: env!("CARGO_PKG_VERSION").to_string(),
                title: None,
                description: Some(API_DESCRIPTION.to_string()),
                icons: None,
                website_url: None,
            },
            instructions: Some(format!(
                "Standalone MCP server for {}. Generated by workflow:api_graduate.",
                API_NAME
            )),
        }
    }
}

// â”€â”€â”€ ENTRY POINT â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

#[tokio::main]
async fn main() -> Result<()> {
    // Stderr-only logging (stdout is reserved for MCP framing)
    tracing_subscriber::fmt()
        .with_writer(std::io::stderr)
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "info".into()),
        )
        .init();

    let service = ApiTool::new()
        .serve(rmcp::transport::stdio())
        .await
        .context("failed to start MCP service")?;

    service.waiting().await?;
    Ok(())
}
